# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 919fb6adbf8cdb77d22dcbfcd5d2f3613fcc9936cc074d66228a4c528cc05d61abb15815551653ceb1d263dd552a56b0d62989cb418dd0e0ae6ee3a28795669e

test:
  secret_key_base: ef9c76e7768098cfbad10f0f6e6c911b2dcff488a66c325167ed281ba815b2c1f275f70e4fd47ed55fc075c34d3f9aea6a5de9ffb69f882e387853d18436719d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
